name: CI

on:
  push:
    branches: [ develop-ffv ]
  pull_request:
    branches: [ develop-ffv ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm i gulp yarn
          yarn
          gulp
      - name: Archive build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
          
